### ISSUE TITLE
[BUG] Licence statement needs consideration

### ISSUE THREAD

**Issue by claremacrae** [obsidian-community/obsidian-theme-template#4]
The README says to change the licence if you want - but the current licence says:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

I'm not sure how those two statements are compatible?

**Comment by chrisgrieser** [comment]
oh, good point. I added the MIT license as sample license _for the theme_, and not as license of *this template repo* 🙈

**Comment by chrisgrieser** [comment]
okay, to avoid that problem, I simply removed the license and the mentioning of adding a license from this repo.

The "how to add your theme" guide and the obsidian releases repo both mention that you should add a license, so it should be fine not having a sample license / license reminder here.

**Comment by claremacrae** [comment]
It’s tricky. I don’t have a good solution. 

If this repo does not have a license, are people allowed to copy it?

**Comment by chrisgrieser** [comment]
Not certain. If the [Obsidian sample plugin](https://github.com/obsidianmd/obsidian-sample-plugin) is any kind of reference, it doesn't seem to have any license.

**Comment by claremacrae** [comment]
@chrisgrieser I don’t think this can be closed - see my comment above.

**Comment by claremacrae** [comment]
> Not certain. If the [Obsidian sample plugin](https://github.com/obsidianmd/obsidian-sample-plugin) is any kind of reference, it doesn't seem to have any license.

Oh brilliant. I buy that. Thank you!
